# Generated by Django 6.0.2 on 2026-03-01 21:38

from django.db import migrations


def migrate_teacher_data(apps, schema_editor):
    """Переносит учителя из старого поля в новое ManyToMany"""
    Student = apps.get_model('school', 'Student')
    
    # Для каждого ученика добавляем учителя в новое поле
    for student in Student.objects.all():
        # Старое поле teacher_id всё ещё существует в БД на этом этапе
        # Но в модели его уже нет, поэтому используем raw query или оставляем как есть
        # Проще: если данные уже загружены, просто проставьте учителей вручную в админке
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_student_options_alter_teacher_options_and_more'),
    ]

    operations = [
    ]
